"""
主题编辑字段定义

THEME_FIELDS — 管理面板中每个可编辑色块的元信息（json_key, 标签, 类别）
"""

# ============================================================
# 主题编辑字段定义
# ============================================================

THEME_FIELDS = [
    # (json_key, 通俗标签, 类别)
    ("cyber_yellow", "标题/高亮文字", "界面主色"),
    ("cyber_cyan", "数据/数值文字", "界面主色"),
    ("cyber_magenta", "装饰品红", "界面主色"),
    ("cyber_orange", "警告提示色", "界面主色"),
    ("cyber_red", "错误/入库标注", "界面主色"),
    ("cyber_green", "成功/出库标注", "界面主色"),
    ("cyber_blue", "辅助蓝色", "界面主色"),
    ("dark_bg", "窗口背景", "面板背景"),
    ("panel_bg", "页面底色", "面板背景"),
    ("card_bg", "输入框/卡片底色", "面板背景"),
    ("border", "所有边框线", "面板背景"),
    ("text", "正文/日志文字", "面板背景"),
    ("text_dim", "提示/次要文字", "面板背景"),
    ("label_default", "统计标签文字", "面板背景"),
    ("panel_darkest", "最深底色（日志/配色区）", "面板背景"),
    ("panel_deeper", "次深底色（代码框）", "面板背景"),
    ("color_vaulted", "遗物出库标注色", "遗物状态"),
    ("color_available", "遗物入库标注色", "遗物状态"),
    ("color_unknown", "遗物未知标注色", "遗物状态"),
    ("color_gold", "金部件（稀有）", "部件稀有度"),
    ("color_silver", "银部件（罕见）", "部件稀有度"),
    ("color_copper", "铜部件（常见）", "部件稀有度"),
    ("log_ok", "日志 [成功]", "日志颜色"),
    ("log_warn", "日志 [警告]", "日志颜色"),
    ("log_error", "日志 [错误]", "日志颜色"),
    ("log_info", "日志 [信息]", "日志颜色"),
    ("log_debug", "日志 [调试]", "日志颜色"),
    ("log_timestamp", "日志 时间戳", "日志颜色"),
    ("btn_default_bg", "普通按钮 背景", "按钮样式"),
    ("btn_default_text", "普通按钮 文字", "按钮样式"),
    ("btn_default_border", "普通按钮 边框", "按钮样式"),
    ("btn_hover_bg", "普通按钮 悬停背景", "按钮样式"),
    ("btn_hover_text", "普通按钮 悬停文字", "按钮样式"),
    ("btn_hover_border", "普通按钮 悬停边框", "按钮样式"),
    ("btn_pressed_bg", "普通按钮 按下背景", "按钮样式"),
    ("btn_disabled_bg", "禁用按钮 背景", "按钮样式"),
    ("btn_disabled_text", "禁用按钮 文字", "按钮样式"),
    ("btn_disabled_border", "禁用按钮 边框", "按钮样式"),
    ("primary_bg", "蓝色主按钮 背景", "按钮样式"),
    ("primary_text", "蓝色主按钮 文字", "按钮样式"),
    ("primary_border", "蓝色主按钮 边框", "按钮样式"),
    ("primary_hover_bg", "蓝色主按钮 悬停背景", "按钮样式"),
    ("primary_hover_border", "蓝色主按钮 悬停边框", "按钮样式"),
    ("primary_disabled_bg", "蓝色主按钮 禁用背景", "按钮样式"),
    ("primary_disabled_text", "蓝色主按钮 禁用文字", "按钮样式"),
    ("primary_disabled_border", "蓝色主按钮 禁用边框", "按钮样式"),
    ("danger_text", "红色危险按钮 文字", "按钮样式"),
    ("danger_border", "红色危险按钮 边框", "按钮样式"),
    ("danger_hover_bg", "红色危险按钮 悬停背景", "按钮样式"),
    ("danger_hover_text", "红色危险按钮 悬停文字", "按钮样式"),
    ("success_text", "绿色成功按钮 文字", "按钮样式"),
    ("success_border", "绿色成功按钮 边框", "按钮样式"),
    ("success_hover_bg", "绿色成功按钮 悬停背景", "按钮样式"),
    ("success_hover_text", "绿色成功按钮 悬停文字", "按钮样式"),
    ("brand_bilibili", "B站链接 默认色", "外链品牌"),
    ("brand_bilibili_hover", "B站链接 悬停色", "外链品牌"),
    ("brand_github", "GitHub链接 默认色", "外链品牌"),
    ("brand_github_hover", "GitHub链接 悬停色", "外链品牌"),
    ("overlay_crosshair_color", "截图准星", "游戏覆盖层"),
    ("overlay_selection_border", "截图框选边框", "游戏覆盖层"),
    ("progress_gradient_start", "进度条 左端色", "游戏覆盖层"),
    ("progress_gradient_mid", "进度条 中间色", "游戏覆盖层"),
    ("progress_gradient_end", "进度条 右端色", "游戏覆盖层"),
    ("fetch_manual_hint", "下载提示色", "游戏覆盖层"),
    ("fetch_error_color", "下载失败色", "游戏覆盖层"),
]
